### ISSUE TITLE
The krogoth branch has binaries for 23.1, but your kernel is at 23.2

### ISSUE THREAD

**Issue by pauldotknopf** [madisongh/meta-tegra#1]
See [here](https://github.com/madisongh/meta-tegra/tree/526f3249e341a767802436427cb17b0becf847ba/recipes-bsp/tegra-binaries).

Do you plan to update this? Is this an issue at run-time? Care for a pull-request?

**Comment by madisongh** [comment]
Now at R24.1/JetPack 2.2 on krogoth and master.  Not planning on updating the jethro branch, but would entertain a pull request there if the tegra-binaries packages need updating for 23.2.

**Comment by madisongh** [comment]
With R24.2 near at hand, will continue to try and keep up with the latest.
