### ISSUE TITLE
CUDA 9.2

### ISSUE THREAD

**Issue by ilyaikik** [madisongh/meta-tegra#118]
Hi!
I'm trying to compile pytorch\caffe2 on Jetson TX2.
- caffe2 configuring and compilation is failed because of gcc-6 (std::tuple not supported in cuda 9.0, but suported in CUDA 9.2). It suggests to use CUDA_HOST_COMPILER gcc-5.
- and I cannot bitbake `thud` with gcc-5.4 because of too much errors

Are you planning to support CUDA 9.2 in your layer?
How can I bitbake gcc-5.4 rpm to install second gcc on board?
Is there any way to use gcc-5.4 on image compiled with gcc-6?
Thank you!

**Comment by ilyaikik** [comment]
Thank you for explanation!
As far as I know, poky-thud goes without gcc-5 layer. Where did you get gcc-5 layer to make your test?
Thank you!

**Comment by madisongh** [comment]
I copied them into the distro layer I use for testing from an older OE-Core version ([here](https://github.com/madisongh/test-distro/tree/thud/layers/meta-testdistro/recipes-devtools/gcc5)). You can also try using the [meta-linaro-toolchain](http://git.linaro.org/openembedded/meta-linaro.git) layer, which maintains older versions of gcc and binutils. I've done that in the past, but found it slightly harder to get that integrated into my builds.

**Comment by ilyaikik** [comment]
Thank you! That helps!
Good luck in supporting this great layer!
