### ISSUE TITLE
Please help! doflash.sh: ERR: unsupported board revision D01

### ISSUE THREAD

**Issue by mwcoop** [madisongh/meta-tegra#120]
I just received a new Jetson TX2 development kit. I have been happily developing on an older board for quite some time using meta-tegra.

My current build uses the sumo Yocto release and corresponding meta-tegra branch. Sadly, I just tried to flash the new board and it is failing completely with the above error. I am in a bind and need this board working ASAP. Any help on resolving this is truly appreciated.

**Comment by philipc** [comment]
See https://github.com/madisongh/meta-tegra/issues/119#issuecomment-452759742
