### ISSUE TITLE
error parsing tegra-minimal-initramfs.bb

### ISSUE THREAD

**Issue by d-wang03** [madisongh/meta-tegra#121]
Hello, when I try to build core-image-sato, the bitbake returns an error:

ERROR: /home/supervisor/osbuilder/bstos/meta-tegra/recipes-core/images/tegra-minimal-initramfs.bb: No IMAGE_CMD defined for IMAGE_FSTYPES entry 'cpio.gz.cboot.bup-payload' - possibly invalid type name or missing support class

Is there any way to fix it ?

Best Regards

**Comment by d-wang03** [comment]
It's my fault for missing extra image settings. 
Sorry to bother.

**Comment by MartinBagge** [comment]
How did you resolve this issue?

**Comment by kekiefer** [comment]
What was your fix for this? I have been working around by bringing in `image_types_tegra` into tegra-minimal-initramfs.bb (kekiefer/meta-tegra@c7796aebf) and this works for me, and seems like a reasonable thing to do, but I'm wondering why it wasn't done this way.

**Comment by madisongh** [comment]
Just add
```
IMAGE_CLASSES += "image_types_tegra"
```
to your `local.conf`.
