### ISSUE TITLE
u-boot for jetson-xavier

### ISSUE THREAD

**Issue by acostach** [madisongh/meta-tegra#123]
Hi,

Is there any plan to have u-boot support for Xavier?

Thanks

**Comment by madisongh** [comment]
No, since NVIDIA isn't providing u-boot for Xavier in Jetpack/L4T. It's been a while since I've looked at the threads on this in their dev forum, but last I looked, u-boot was not in the roadmap at all.

**Comment by acostach** [comment]
I see.. Thanks a lot for confirming @madisongh
