### ISSUE TITLE
Linux 4 Tegra 28.3

### ISSUE THREAD

**Issue by compiaffe** [madisongh/meta-tegra#125]
The new L4T 28.3 is out. Will there be an updated release matching this?
https://developer.nvidia.com/embedded/linux-tegra-r283

**Comment by madisongh** [comment]
I'm working on it.

**Comment by madisongh** [comment]
Now available on the [thud-l4t-r28.3](https://github.com/madisongh/meta-tegra/tree/thud-l4t-r28.3) branch.
