### ISSUE TITLE
L4T R32.1 TX2

### ISSUE THREAD

**Issue by sjdrc** [madisongh/meta-tegra#128]
Hi there,

What is the current status of the R32.1 branch? I assume that this is required for using applications compiled for CUDA 10 and TRT5.

Please let me know if there's anything I can do to help.

**Comment by madisongh** [comment]
The R32.1 support is present on the `warrior` branch and in `master`. See [this wiki page](https://github.com/madisongh/meta-tegra/wiki/L4T-R32.1.0-Notes) for details.
 
Patches are welcome to fix any problems you might run into.
