### ISSUE TITLE
Please confirm flashing for nano

### ISSUE THREAD

**Issue by outbackdingo** [madisongh/meta-tegra#131]
Ive got the image built, following these instructions, i dd the sdcard image to the sdcard on my dev machine, place it in the nano, power it on.... do i then also have to continue with the REC / RST and sudo flashing routines.... or is the sdcard image the full bootable image

For Jetson Nano, you will also need the SDcard image: <image-type>-${MACHINE}.sdcard. Copy that image onto an SDcard directly from you development machine with dd if=<image-name> of=/dev/<sdcard-device> bs=1M conv=fsync. You may need to use sudo for this. The default SDcard image size is 16GiB, so this could take a few minutes. Once done, properly eject the SDcard from your host and insert it into the slot on the underside of the Nano module.

Now, make sure the board is plugged in and powered on before continuing.

Plug a micro-USB cable into the board's USB0 port and connect it to your host machine.

On your board, while holding the recovery button (REC), press reset (RST) to boot into recovery mode. You'll see the lights briefly flash off and on. You may need to hold the REC button down for at least three seconds after releasing RST to have the device fully switch to recovery mode.

Now, simply sudo ./doflash.sh, wait for it to do its thing, and voila! The script will cold-reboot the Jetson, and you've got a hot new image flashed!

Note: Depending on your python configuration, you may need to modify the second line of doflash.sh from something like tegraflash.py --bl cboot.bin... to python tegraflash.py --bl cboot.bin...

**Comment by madisongh** [comment]
The jetson-nano tegraflash package flashes *only* the QSPI boot flash. Near as I can tell, this should only need to be done once, unless there is an L4T update that changes the bootloader files.
The rootfs, U-boot, etc. get placed into partitions in the SDcard image.

If you're only making changes to the kernel or the rootfs, you shouldn't even need to reformat the entire SDcard to make updates after the first time - just use `dd` to copy the ext4 filesystem image of the rootfs into the first partition on it.
