### ISSUE TITLE
Bzip2 Issue with Nvidia Source Tarball

### ISSUE THREAD

**Issue by phishstang65** [madisongh/meta-tegra#141]
The Nvidia provided source file located at the following link cannot be decompressed with bzip2 1.0.6 provided by the OE Layer:
`https://devtalk.nvidia.com/default/topic/1056301/b/t/post/5355418/`

The issue seems to be fixed by upgrading bzip2 to the latest version:
`https://www.sourceware.org/bzip2/downloads.html`

This issue is detailed in the following posts:
`https://devtalk.nvidia.com/default/topic/1056301/b/t/post/5355418/`
`https://devtalk.nvidia.com/default/topic/1056381/jetson-agx-xavier/jetpack-4-2-xavier-install-failed/1`

**Comment by madisongh** [comment]
It's actually using your build host's version of bzip2, but yeah, I had the same problem over the weekend.  I worked around it by installing `lbzip2` on my host (Ubunut, so `sudo apt install lbzip2`), then setting up my PATH so a `bzip2` symlink pointing at `/usr/bin/lbzip2` would come first.

**Comment by phishstang65** [comment]
Thanks.
