### ISSUE TITLE
l4t 32.2 integration

### ISSUE THREAD

**Issue by acostach** [madisongh/meta-tegra#155]
Hey Matt, not an actual issue more like a question, are you planning to bring in the new l4t 32.2 too? I know it's just been released end of last week but wanted to know if you have any estimate of a wip branch or anything.

Thanks a lot!

**Comment by madisongh** [comment]
Yep, it's in the works. Once I'm a bit further along, I'll push a branch with the work in progress.  Can't promise a particular timeline, but hopefully within the next week or so.

**Comment by acostach** [comment]
Sounds great, thank you!
