### ISSUE TITLE
Configure remote VNC on Jetson?

### ISSUE THREAD

**Issue by mwcoop** [madisongh/meta-tegra#159]
Hello,

I'm trying to get a VNC configuration working on Jetson Nano/TX2/Xavier. So far I have tried adding tigervnc and x11vnc to my Yocto image. Everything builds fine. However, both programs complain about not finding "xauth."

My image is core-image-weston + other stuff. Any ideas/tips/success stories getting VNC added to a meta-tegra image?

**Comment by madisongh** [comment]
I don't think VNC is an option if you're using Weston, from what I've read.  You could try using FreeRDP (recipe in meta-oe), and adding `--enable-rdp-compositor` in your weston build to enable it.

**Comment by mwcoop** [comment]
Ahh. Excellent information. Thanks.

On a somewhat related note. I got Weston+FreeRDP working. However, on my Jetson Xavier, I only get a black screen via HDMI. Does that need something specific? Can I have them working simultaneously?

**Comment by madisongh** [comment]
I suspect you need to have two weston services - one for RDP and one for the real display device. You may have to assign them different seat IDs as well, if weston can't figure that out for itself.
