### ISSUE TITLE
nvidia packages changed from xxx.166-xxxx to xxx.326-xxx

### ISSUE THREAD

**Issue by miccom86** [madisongh/meta-tegra#171]
Hello I changed the name of the packages from  xxx.166-xxxx to xxx.326-xxx because now the nvidia pakage download those packages (ubuntu 16.04 and ubuntu 18.04 are equivalent) :

cuda.csv
cuda-repo-cross-aarch64-10-0-local-10.0.326_1.0-1_all.deb
cuda-repo-l4t-10-0-local-10.0.326_1.0-1_arm64.deb
cuda-repo-ubuntu1804-10-0-local-10.0.326-410.108_1.0-1_amd64.deb
cudnn.csv
devtools_docs.zip
graphsurgeon-tf_5.1.6-1+cuda10.0_arm64.deb
Jetson-210_Linux_R32.2.0_aarch64.tbz2
libcudnn7_7.5.0.56-1+cuda10.0_arm64.deb
libcudnn7-dev_7.5.0.56-1+cuda10.0_arm64.deb
libcudnn7-doc_7.5.0.56-1+cuda10.0_arm64.deb
libnvidia-container0_0.9.0~beta.1_arm64.deb
libnvidia-container-tools_0.9.0~beta.1_arm64.deb
libnvinfer5_5.1.6-1+cuda10.0_arm64.deb
libnvinfer-dev_5.1.6-1+cuda10.0_arm64.deb
libnvinfer-samples_5.1.6-1+cuda10.0_all.deb
libopencv_3.3.1-2-g31ccdfe11_arm64.deb
libopencv_3.3.1-2-gb3f86dcd5_amd64.deb
libopencv-dev_3.3.1-2-g31ccdfe11_arm64.deb
libopencv-dev_3.3.1-2-gb3f86dcd5_amd64.deb
libopencv-python_3.3.1-2-g31ccdfe11_arm64.deb
libopencv-python_3.3.1-2-gb3f86dcd5_amd64.deb
libopencv-samples_3.3.1-2-g31ccdfe11_arm64.deb
libopencv-samples_3.3.1-2-gb3f86dcd5_amd64.deb
libvisionworks-repo_1.6.0.500n_amd64.deb
libvisionworks-repo_1.6.0.500n_arm64.deb
libvisionworks-sfm-repo_0.90.4_amd64.deb
libvisionworks-sfm-repo_0.90.4_arm64.deb
libvisionworks-tracking-repo_0.88.2_amd64.deb
libvisionworks-tracking-repo_0.88.2_arm64.deb
NsightSystems-linux-public-2019.4.1.10-a76094a.deb
nvidia-container-runtime_0.9.0_beta.1+docker18.09.2-1_arm64.deb
nvidia-container-runtime-hook_0.9.0_beta.1-1_arm64.deb
nvidia-docker2_0.9.0_beta.1+docker18.09.2-1_arm64.deb
NVIDIA_VisionWorks_References.zip
python3-libnvinfer_5.1.6-1+cuda10.0_arm64.deb
python3-libnvinfer-dev_5.1.6-1+cuda10.0_arm64.deb
python-libnvinfer_5.1.6-1+cuda10.0_arm64.deb
python-libnvinfer-dev_5.1.6-1+cuda10.0_arm64.deb
sdkml3_jetpack_l4t_421_b100_rev1.json
Tegra_Linux_Sample-Root-Filesystem_R32.2.0_aarch64.tbz2
Tegra_Multimedia_API_R32.2.0_aarch64.tbz2
tensorrt_5.1.6.1-1+cuda10.0_arm64.deb
tensorrt.csv
uff-converter-tf_5.1.6-1+cuda10.0_arm64.deb
visionworks.csv

But I reach the following error:

cp: cannot stat '/home/fmocci/jetson/19-ago-2019/dev-jetson-yocto/build/tmp/work/armv8a_tegra210-poky-linux/cuda-misc-headers/10.0.326-1-r0/build/usr/*': No such file or directory

the folder.../build is empty.
Ths usr folder is present into the following paths:
../image/usr
../recipe-sysroot-native/usr
../recipe-sysroot/usr

But there are also other errors if I try to put those paths

Can you support the new name of nvidia  packages?

**Comment by madisongh** [comment]
The 10.0.166 versions are from JetPack 4.2, which goes with L4T R32.1; the 10.0.326 versions are from JetPack 4.2.1, which goes with L4T R32.2.

If you're using the warrior branch, you need the JetPack 4.2 packages; to get them, Click on the `...` in the bottom right corner of the "TARGET OPERATING SYSTEM" box in the NVIDIA `sdkmanager` application and choose "JetPack 4.2" (instead of the default "JetPack 4.2.1 (rev. 1)").

If you need to use the JetPack 4.2.1 packages, you could switch to the [warrior-l4t-r32.2](https://github.com/madisongh/meta-tegra/tree/warrior-l4t-r32.2) branch I created over the weekend.
