### ISSUE TITLE
nvbootctrl does not work on scarthgap builds using systemd and overlayfs-etc

### ISSUE THREAD

**Issue by emrodre** [madisongh/meta-tegra#1767]
**Describe the bug**

`nvbootctrl dump-slots-info` does not work on a Scarthgap core-image-base
build for Jetson Orin NX when using systemd and overlayfs-etc, but it does for
Kirsktone using the same config.

Expected output:

```
root@p3768-0000-p3767-0001:~# nvbootctrl dump-slots-info
Current version: 36.4.0
Capsule update status: 0
Current bootloader slot: A
Active bootloader slot: A
num_slots: 2
slot: 0,             status: normal
slot: 1,             status: normal
```

Actual output:

```
root@p3768-0000-p3767-0001:~# nvbootctrl dump-slots-info
Current version: 36.4.0
Capsule update status: 0
Error: read variable BootChainFwCurrent failed!
Error: invalid current bootloader slot: return(-22)
```

I've tested the following combinations and it only fails when using both
systemd and overlayfs-etc:

| Yocto Relase | systemd | overlayfs-etc | nvbootctrl works |
| ------------ | ------- | ------------- | ---------------- |
| Scarthgap    | y       | y             | n                |
| Scarthgap    | y       | n             | y                |
| Scarthgap    | n       | y             | y                |
| Kirkstone    | y       | y             | y                |

Full boot logs and Kas config files for each test are attached.

**To Reproduce**

1. Install Siemens Kas (https://github.com/siemens/kas)
2. Build with `kas build config-file.yaml`
3. Extract tegraflash.tar.gz build
4. Flash with `sudo ./initrd-flash --erase-nvme
5. On the target machine: `nvbootctrl dump-slots-info`

[scarthgap-systemd-kas-config.yaml.txt](https://github.com/user-attachments/files/17834701/scarthgap-systemd-kas-config.yaml.txt)
[scarthgap-systemd-boot-log.txt](https://github.com/user-attachments/files/17834687/scarthgap-systemd-boot-log.txt)

[scarthgap-systemd-no-overlayfs-etc-kas-config.yaml.txt](https://github.com/user-attachments/files/17834702/scarthgap-systemd-no-overlayfs-etc-kas-config.yaml.txt)
[scarthgap-systemd-no-overlayfs-etc-boot-log.txt](https://github.com/user-attachments/files/17834688/scarthgap-systemd-no-overlayfs-etc-boot-log.txt)

[scarthgap-no-systemd-kas-config.yaml.txt](https://github.com/user-attachments/files/17834700/scarthgap-no-systemd-kas-config.yaml.txt)
[scarthgap-no-systemd-boot-log.txt](https://github.com/user-attachments/files/17834686/scarthgap-no-systemd-boot-log.txt)

[kirkstone-systemd-kas-config.yaml.txt](https://github.com/user-attachments/files/17834699/kirkstone-systemd-kas-config.yaml.txt)
[kirkstone-systemd-boot-log.txt](https://github.com/user-attachments/files/17834685/kirkstone-systemd-boot-log.txt)

**Comment by dwalkes** [comment]
My first suspicion is a sequencing issue, see https://github.com/OE4T/meta-tegra/discussions/1634#discussioncomment-11103687

**Comment by dwalkes** [comment]
I think it typically happens [here](https://github.com/OE4T/meta-tegra/blob/f3770ccd46259d0f2af6835d3b885fedb8d31ad5/recipes-core/initrdscripts/tegra-minimal-init/init-boot.sh#L6) in tegra-minimal-init.   Perhaps it gets unmounted as a part of the overlayfs-etc init setup and then never remounted?

**Comment by dwalkes** [comment]
Thanks, I think that makes sense. The more general fix is probably a check in the overlayfs-etc script to see if /sys is already mounted and skip mounting if it is.
