### ISSUE TITLE
'ERR: flash variable set not defined' in U-Boot build.

### ISSUE THREAD

**Issue by madscientist42** [madisongh/meta-tegra#177]
Fails as described in the title.  Target is a TX2.

**Comment by madscientist42** [comment]
X-D   I'd figured that it was likely something like this.  I'm using a machine that adds a few features on top of the jetson-tx2 one.  Initially, we'd needed it to add +crc+crypto on top of the stock config since we needed and the TX2 provided the same.  Subsequently, it's gotten a few other feature items on top of it and I'm using it to trigger our move to GCC 7.3 (Which there's a layer in my github repos, for those tracking these things, that provides this for Warrior correctly.) since we might have SOCs that don't need that.

Is this characteristic documented obviously and I just flat missed it with my trying to bring this all to 4.2.1 and then doing my intended move to provide a production ready cross-compile SDK?

**Comment by madscientist42** [comment]
Oh, and thanks for the quick response.  :D

**Comment by madisongh** [comment]
> Is this characteristic documented obviously and I just flat missed it 

Not really.  Probably should add a wiki page about defining new machines.

**Comment by klutchell** [comment]
+1 for a wiki page

I'm in the process of defining a new machine right now based on jetson-tx2-4GB and once I got past the u-boot error above I started looking at how to override the flashvars file with one from my own layer & machine. I'll get there eventually but a wiki page would be extremely helpful.

**Comment by madscientist42** [comment]
We do need to work on docs...  That was a pretty nifty sharp edge to cut myself on.  X-D

**Comment by madscientist42** [comment]
Gonna leave this open for now so we have it for people to find if they trip across it until we all can get Wiki, etc. defined for it all.

**Comment by lfdmn** [comment]
I came shopping for similar answer =)

In my case, I've merged ConnectTect kernel sources.

I have a meta-connecttech layer where I change the kernel repository and define 3 machines:
* astro-tx2
* elroy-tx2
* elroy-pcie-tx2.conf

My file layout is:
* meta-connecttech/recipes-bsp/tegra-binaries/files
  * astro-tx2
    * flashvars
  * elroy-mpcie-tx2
    * flashvars
  * elroy-tx2
    * flashvars

@madisongh how in meta-tegra file/**jetson-tx2**/flashvars and others are fetched? I've been looking through the recipes and don't find who is taking them.

As I understand I should bbappend tegra-flashvars_32.2.0. That'd work for one MACHINE but how about 3? I recall with yocto we can have FILEEXTRAPATHS_prepend_${SOC_FAMILY} but not FILEEXTRAPATHS_prepend_${MACHINE}

Here's a sample of astro-tx2 definition:
```
#@TYPE: Machine
#@NAME: Nvidia Astro TX2
#@DESCRIPTION: Nvidia Jetson TX2 on ConnectTech Astro

# Comes from meta-tegra
require conf/machine/include/tegra186.inc

KERNEL_DEVICETREE ?= "_ddot_/_ddot_/_ddot_/_ddot_/nvidia/platform/t18x/quill/kernel-dts/tegra186-tx2-cti-ASG001-revG+.dtb"

MACHINE_FEATURES += "ext2 ext3 vfat"

UBOOT_MACHINE = "p2771-0000-500_defconfig"

EMMC_SIZE ?= "31276924928"
EMMC_DEVSECT_SIZE ?= "512"
BOOTPART_SIZE ?= "8388608"
BOOTPART_LIMIT ?= "10485760"
ROOTFSPART_SIZE ?= "12884901888"
ODMDATA ?= "0x6090000"
EMMC_BCT ?= "P3310_A00_8GB_Samsung_8GB_lpddr4_204Mhz_A02_l4t.cfg"
NVIDIA_BOARD ?= "t186ref"
TEGRA186_REDUNDANT_BOOT ?= "0"
PARTITION_LAYOUT_TEMPLATE ?= "flash_l4t_t186.xml"
```

**Comment by madisongh** [comment]
@lfdmn bitbake will automatically populate its file search path based on OVERRIDES, so you don't need to use any extra overrides on FILESEXTRAPATHS.  In your layer, just add a `recipes-bsp/tegra-binaries/tegra-flashvars_32.2.0.bbappend` (or use the `%` wildcard for the version number, if you want) with this one line:
```
FILESEXTRAPATHS_prepend := "${THISDIR}/files:"
```
then for each MACHINE, put the specific `flashvars` file into a `files/${MACHINE}` subdirectory.  bitbake will take care of setting up the search path under `files` for you.

**Comment by madisongh** [comment]
I have added [a wiki page](https://github.com/madisongh/meta-tegra/wiki/Creating-a-custom-MACHINE) on how to create a custom MACHINE definition. Feel free to update/expand as needed.

**Comment by madscientist42** [comment]
Will do.
