### ISSUE TITLE
jetson-tx2-4gb: Cannot find partition mts-bootpack

### ISSUE THREAD

**Issue by klutchell** [madisongh/meta-tegra#179]
I'm trying to add support for Jetson-TX2-4GB variation as described in `L4T-tegra186-32.2.0-r0/Linux_for_Tegra/jetson-tx2-4GB.conf`:

```
# p2771-0000-0888.conf: configuration for T186-A02 te770m P3489 SKU888

BPFDTB_FILE=tegra186-a02-bpmp-lightning-p3489-a00-00-te770m.dtb;
source "${LDK_DIR}/p2771-0000.conf.common";
EMMC_BCT=P3489_Sku888_4GB_Hynix_4GB_lpddr4_204Mhz_P138_A02_l4t.cfg
DTB_FILE=tegra186-quill-p3489-0888-a00-00-base.dtb;
TBCDTB_FILE=tegra186-quill-p3489-0888-a00-00-base.dtb;

PROD_CONFIG="tegra186-mb1-bct-prod-storm-p3489-1000-a00.cfg";
PINMUX_CONFIG="tegra186-mb1-bct-pinmux-quill-p3489-1000-a00.cfg";
PMIC_CONFIG="tegra186-mb1-bct-pmic-lightning-p3489-1000-a00.cfg";
PMC_CONFIG="tegra186-mb1-bct-pad-quill-p3489-1000-a00.cfg";
BOOTROM_CONFIG="tegra186-mb1-bct-bootrom-quill-p3489-1000-a00.cfg";
ROOTFSSIZE=14GiB;
```

I've created a custom machine based on jetson-tx2, and a flashvars overlay with the values from above mapped in and added to `FILESEXTRAPATHS_prepend`. From the doflash log it appears all of my values are being used as expected.

**conf/machine/jetson-tx2-4gb.conf:**
```
#@TYPE: Machine
#@NAME: jetson-tx2-4gb
#@DESCRIPTION: Machine configuration for Jetson-TX2-4GB

MACHINEOVERRIDES = "jetson-tx2:${MACHINE}"
KERNEL_DEVICETREE ?= "_ddot_/_ddot_/_ddot_/_ddot_/nvidia/platform/t18x/quill/kernel-dts/tegra186-quill-p3489-0888-a00-00-base.dtb"
EMMC_BCT ?= "P3489_Sku888_4GB_Hynix_4GB_lpddr4_204Mhz_P138_A02_l4t.cfg"
ROOTFSSIZE = "14GiB"

include conf/machine/jetson-tx2.conf
```
**recipes-bsp/tegra-binaries/files/jetson-tx2-4gb/flashvars:**
```
FLASHVARS="BPFDTB_FILE PINMUX_CONFIG PMIC_CONFIG PMC_CONFIG PROD_CONFIG BOOTROM_CONFIG MISC_CONFIG SCR_CONFIG SCR_COLD_BOOT_CONFIG DEV_PARAMS"
BPFDTB_FILE=tegra186-a02-bpmp-lightning-p3489-a00-00-te770m.dtb
PINMUX_CONFIG=tegra186-mb1-bct-pinmux-quill-p3489-1000-a00.cfg
PMIC_CONFIG=tegra186-mb1-bct-pmic-lightning-p3489-1000-a00.cfg
PMC_CONFIG=tegra186-mb1-bct-pad-quill-p3489-1000-a00.cfg
PROD_CONFIG=tegra186-mb1-bct-prod-storm-p3489-1000-a00.cfg
BOOTROM_CONFIG=tegra186-mb1-bct-bootrom-quill-p3489-1000-a00.cfg
MISC_CONFIG=tegra186-mb1-bct-misc-si-l4t.cfg
SCR_CONFIG=minimal_scr.cfg
SCR_COLD_BOOT_CONFIG=mobile_scr.cfg
DEV_PARAMS=emmc.cfg
```

However flashing never succeeds. It always fails when attempting to write mts-bootpack.
```
[   5.8439 ] Writing partition APP with core-image-minimal.img
[   5.8470 ] [................................................] 100%
[  24.7333 ] Writing partition mts-bootpack with mce_mts_d15_prod_cr_sigheader.bin.encrypt
[  24.7548 ] 000000000d0d000d: o open partition %s.
[  24.7703 ] 
[  24.7704 ] 
Error: Return value 13
Command tegradevflash_v2 --pt flash.xml.bin --create
```
```
[0012.017] I> Writing APP partition.
[0030.924] I> Writing mts-bootpack partition.
[0030.928] E> Cannot find partition mts-bootpack
[0030.932] E> NV3P_SERVER: Failed to open partition mts-bootpack.
```

I thought this was a fairly simple overlay but it's giving me more trouble that I expected. Have you seen anything like this before? Is it related to the `oem_sign` flag not validating?

Sorry for the verbose copy paste - I don't have the files on a public repo yet for linking. If I can get this working I would be happy to submit a pull request as it's a board variation supported by Nvidia.

**Comment by madisongh** [comment]
You shouldn't need the `MACHINEOVERRIDES` setting in the machine configuration file, but otherwise that all looks right.  If you can shoot me a copy of the full log of a `flash.sh` run  from the stock L4T, a full log of your failed flashing from your meta-tegra build, and a listing of the contents of the `tegraflash.zip` package, I'll take a look and see if I can help track down the problem.

**Comment by klutchell** [comment]
Solved. After staring at it for over a week and comparing every file used in the doflash log to the stock flash log.

I finally noticed that the `ROOTFSSIZE = "14GiB"` value I had copied from `L4T-tegra186-32.2.0-r0/Linux_for_Tegra/jetson-tx2-4GB.conf` was not being used.

Once I converted it to `ROOTFSPART_SIZE ?= "15032385536"` the doflash went perfectly. Here's my current `jetson-tx2-4gb.conf`.

```
#@TYPE: Machine
#@NAME: Nvidia Jetson TX2 4GB
#@DESCRIPTION: Machine configuration for Nvidia Jetson TX2 4GB variant

KERNEL_DEVICETREE ?= "_ddot_/_ddot_/_ddot_/_ddot_/nvidia/platform/t18x/quill/kernel-dts/tegra186-quill-p3489-0888-a00-00-base.dtb"
ROOTFSPART_SIZE ?= "15032385536"
EMMC_BCT ?= "P3489_Sku888_4GB_Hynix_4GB_lpddr4_204Mhz_P138_A02_l4t.cfg"
TEGRA_BOARDID ?= "3489"
TEGRA_FAB ?= "300"

include conf/machine/jetson-tx2.conf
```

Is this BSP configuration something you would want in the meta-tegra repo? I'd be happy to submit a pull request for the conf and flashvars if you'd like. Otherwise I'll keep it in my custom layer and carry on with my project.

Thanks for all your hard work!

**Comment by madisongh** [comment]
Yes, please do.  Thanks!
