### ISSUE TITLE
How goes the Xorg stuff?

### ISSUE THREAD

**Issue by pauldotknopf** [madisongh/meta-tegra#19]
Last time I checked, you added a patch to supposedly fix Xorg, but it didn't work. Have you been able to successfully get it up and running yet? Maybe the qt5 cinematic experience demo?

If not, if you are interested in some contract work, email me at pauldotknopf@gmail.com.

**Comment by lrvk123** [comment]
I am interested in the subject as well. Paul, what is your current issue with Xorg?

**Comment by madisongh** [comment]
The Xorg situation improved with the L4T R24.2 release.  I've tested core-image-sato images built off the krogoth-l4t-r24.2 branch and the morty branch.
