### ISSUE TITLE
Formatting new partitions (Jetson Nano)

### ISSUE THREAD

**Issue by triblex** [madisongh/meta-tegra#198]
When I add new partitions to the sdcard-layout, where/how do I format the new partitions to ext3/4 or FAT?

**Comment by madisongh** [comment]
You would create a file with the image of the filesystem in it as part of the `tegraflash_custom_pre` function in your image recipe.  For actually creating the filesystem container file, take a look at the `oe_mkext234fs` function in `meta/classes/image_types.bbclass`.  For a FAT filesystem, take a look at the `build_fat_img` function in `meta/classes/image-live.bbclass`.
