### ISSUE TITLE
Nano - Failed to open "sd0:LNX"

### ISSUE THREAD

**Issue by FXRer** [madisongh/meta-tegra#210]
I tried to build a Yocto minimal image for my Jetson Nano but I have some issue booting from the SD card as in the attached log file : 
[Nano_Yocto_Boot.log](https://github.com/madisongh/meta-tegra/files/3853801/Nano_Yocto_Boot.log)

Could you help to support?

Thanks in advance.
pascal

**Comment by madisongh** [comment]
From the 'failed to open partition' messages, it looks like the Nano isn't seeing anything on the SDcard. Double-check that the SDcard you're using is the one you copied the image to, and make sure you've inserted it properly in the slot on the Nano.

**Comment by FXRer** [comment]
It works, thank you again for your support.
