### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by avishorp** [madisongh/meta-tegra#22]
Can you please add some kind of "getting started" to the README file with instructions about building a basic system?

Thanks
Avishay

**Comment by JackKiefer** [comment]
Hey @avishorp. This might not be exactly what you're looking for, but I've added a guide to the wiki about how to flash the TX1 using the image generated using this layer with BitBake. 

If you're more looking for a general quick-start into building a basic image with Yocto/BitBake, that has been [extensively documented here.](https://www.yoctoproject.org/docs/2.3/yocto-project-qs/yocto-project-qs.html)

**Comment by madisongh** [comment]
Thanks for that, @JackKiefer !
