### ISSUE TITLE
What should I set for the FAB (board revision number) for TX2i?

### ISSUE THREAD

**Issue by danielwangksu** [madisongh/meta-tegra#224]
Hi all,

I'm little bit confused by the FAB number. I'm not sure what is the correct number for my TX2i board. The master branch uses "B04` defined in tegra186.inc. The warrior branch uses "B02". My board returns "300". Either number seems to work when I flash the board. Is the number fixed for specific board or it changes depends on firmware? Thank you for your help.

**Comment by madisongh** [comment]
Use the FAB setting mentioned in the NVIDIA secure boot documentation. Whatever they say to use with their scripts should work here.

**Comment by danielwangksu** [comment]
Thanks @madisongh
