### ISSUE TITLE
Static IP in /etc/network/interfaces not taking effect

### ISSUE THREAD

**Issue by mwcoop** [madisongh/meta-tegra#225]
Using a distro based on madisongh/test-distro, I'm finding that /etc/network/interfaces no longer takes effect. My eth0 interface is still using DHCP. I am using systemd as my startup manager.

Have things moved to a new mechanism for configuring interfaces? I see things like dhcpcd and udhcpc aroudn Google. Any pointers on how to get this configured would be greatly appreciated!

**Comment by madisongh** [comment]
OE-Core started defaulting to using systemd-networkd, so I did the same in my test distro.  Take a look at the [systemd.network](https://www.freedesktop.org/software/systemd/man/systemd.network.html#) man page for info on the settings.

**Comment by mwcoop** [comment]
Any particular recipe that I should look at using to overwrite the original configuration?

**Comment by madisongh** [comment]
`systemd-conf` - there's already a [bbappend for it here](https://github.com/madisongh/meta-tegra/blob/master/recipes-core/systemd/systemd-conf_%25.bbappend) where we drop in a Tegra-specific copy of `wired.network`.

**Comment by mwcoop** [comment]
Oddly, I don't see the wired.network file being put into the rootfs. The systemd-conf recipe is being built. Is there a distro setting I might be missing to get this?

**Comment by madisongh** [comment]
It does get renamed as part of the install, and should be at `/lib/systemd/network/80-wired.network`.

**Comment by madisongh** [comment]
@mwcoop did you get this working?  #259 looks like it might have been the same issue.
