### ISSUE TITLE
Question about old Jetson TK1

### ISSUE THREAD

**Issue by dev-0x7C6** [madisongh/meta-tegra#246]
Hi,

Any chance to bring back Jetson TK 1 support (and drop problematic parts)?. I want to bring back my old board to life again :-)

What do you think? 

Offtop:
Anyway thanks for great work. I'm working on libglvnd integration with mesa and I found this repository very helpful.

**Comment by madisongh** [comment]
For an L4T-based build, there's so much that's so old that I had to give up on keeping the TK1 up-to-date with the latest toolchains etc. from OE-Core.  Maybe with the mainline kernel?

**Comment by dev-0x7C6** [comment]
Ok, thanks for advice :)
