### ISSUE TITLE
TX2

### ISSUE THREAD

**Issue by rectoyon** [madisongh/meta-tegra#25]
not really an issue, but any plans to support the TX2? This layer has been very useful for the TX1.

**Comment by madisongh** [comment]
I'm hoping to.  I pre-ordered a Jetson TX2 dev kit, so I'll have the hardware, and hopefully it won't be too much of a stretch to extend the layer to support it as well.

**Comment by rectoyon** [comment]
that's great to hear. looks like different kernels now for TX1/TX2 but they say they'll align them
https://developer.nvidia.com/embedded/jetpack
BTW, feel free to close this issue.
