### ISSUE TITLE
Jetson TX2 only has 4.8GB root partition.

### ISSUE THREAD

**Issue by build2c** [madisongh/meta-tegra#261]
My Jetson TX2 only reports that "/" has 4.8GB of total space. The machine configuration files seem to indicate I should have the full ~30GB. Does something need to be done to ensure all of the storage is allocated to the root partition?

**Comment by madisongh** [comment]
You can set IMAGE_ROOTFS_SIZE to have the rootfs filesystem occupy the entire partition.  For example:
```
IMAGE_ROOTFS_SIZE = "${@int(d.getVar('ROOTFSPART_SIZE')) // 1024}"
```

**Comment by madisongh** [comment]
A change that defaults the IMAGE_ROOTFS_SIZE to fill the rootfs partition went in with #266 and #267.
