### ISSUE TITLE
L4T R32.3.1 for Yocto/OE release Thud 

### ISSUE THREAD

**Issue by leon-anavi** [madisongh/meta-tegra#262]
Hi @madisongh,

I am trying to port L4T R32.3.1 from branch Zeus to a new branch compatible with Yocto/OE release Thud. I am using similar approach as for https://github.com/madisongh/meta-tegra/issues/152. Are you interested in accepting this work upstream and would create branch thud-l4t-r32.3.1 where I can submit my changes?

Thanks,
Leon

**Comment by madisongh** [comment]
Sure.  I just created the new branch for you.

**Comment by leon-anavi** [comment]
Thank you!
