### ISSUE TITLE
Overlay FS

### ISSUE THREAD

**Issue by lfdmn** [madisongh/meta-tegra#276]
Hi,

I have this intramfs script to overlay a read only file system into another partition

```bash
#!/bin/sh
PATH=/sbin:/bin:/usr/sbin:/usr/bin
mount -t proc proc /proc
mount -t devtmpfs none /dev
mount -t sysfs sysfs /sys

rootdev_ro=""
rootdev_rw=""
opt="rw"
wait=""

[ ! -f /etc/platform-preboot ] || . /etc/platform-preboot

if [ -z "$rootdev_ro" ]; then
    for bootarg in `cat /proc/cmdline`; do
    echo "${bootarg}"
    arg=`expr "x$bootarg" : 'x[^=]*=\(.*\)' || echo ''`

	case "$bootarg" in
	    root=*) rootdev_ro="${arg}" ;;
        rootrw=*) rootdev_rw="${arg}" ;;
	    ro) opt="ro" ;;
	    rootwait) wait="yes" ;;
	esac
    done
fi

mkdir -p /mnt/lower
mkdir -p /mnt/upper
mkdir -p /mnt/work
mkdir -p /mnt/overlay

mount -t ext4 -o "ro" "${rootdev_ro}" /mnt/lower
mount -t ext4 -o "rw" "${rootdev_rw}" /mnt/upper
mount -t overlay overlay -o lowerdir=/mnt/lower,upperdir=/mnt/upper,workdir=/mnt/work /mnt/overlay

mount --move /sys  /mnt/overlay/sys
mount --move /proc /mnt/overlay/proc
mount --move /dev  /mnt/overlay/dev
exec switch_root /mnt/overlay /sbin/init
```

Add added in linux-tegra_4.9.bbappend 
`KERNEL_FEATURES_append = " features/overlayfs/overlayfs.scc"`

Mounting rootdev_ro (mmcblk0p1) and rootdev_rw (mmcblk0p32) succeed and both are ETX4-fs

Mounting the overlay fails with error
`mount: mounting overlay on /mnt/overlay failed: No such device`

The minimal image I'm testing with installs kernel-modules.

If I modprobe overlay in the raminitfs script I get error
`modprobe: can't change directory to '/lib/modules': No such file or directory`

What am I missing?

**Comment by madisongh** [comment]
The L4T kernel configs already have CONFIG_OVERLAY_FS enabled, but built as a module.  You'd either have to explicitly add `kernel-module-overlay` to your initramfs image, or (probably better) change CONFIG_OVERLAY_FS to be built-in (`y` instead of `m`).

**Comment by lfdmn** [comment]
Thanks!
