### ISSUE TITLE
NVIDIA_DEVNET_MIRROR mandatory on warrior

### ISSUE THREAD

**Issue by mirzak** [madisongh/meta-tegra#284]
It seems with the update in https://github.com/madisongh/meta-tegra/commit/b5e7cdab655090d7989ef94b169e67837dde85a6#diff-615d50cc49b82960424c074e6054cac2, it is now mandatory to have `NVIDIA_DEVNET_MIRROR` defined or else you get an parse error. 

I do not know if this change was intentional, and I have not really tried how it is on other branches but I wanted to get your feedback on this.

Edit:

Some additionally information, when trying to remove the usage of `NVIDIA_DEVNET_MIRROR` it obviously then fails on applying the patches in `tegra186-flashtools-native_32.1.0.bb:do_patch`,

```
file://0001-Fix-skipuid-arg-usage-for-tx2-in-odmsign.func.patch
file://0002-Update-l4t_bup_gen.func-to-handle-signed-encrypted-b.patch
```

**Comment by madisongh** [comment]
Yeah, unfortunately, the secure boot tools for L4T R32.1 were only available via manual download from NVIDIA's developer network.  I've just put in a change that skips the secure boot tooling support if you don't have NVIDIA_DEVNET_MIRROR set, which should restore the prior behavior if you don't need the devnet extras.

**Comment by mirzak** [comment]
Awesome! Thanks for the quick response and resolve. Closing this
