### ISSUE TITLE
libdrm-dev version conflict during image do_rootfs

### ISSUE THREAD

**Issue by kekiefer** [madisongh/meta-tegra#290]
I started noticing errors like this recently on master builds during `do_rootfs` of my image:

```
Exception: FileNotFoundError: [Errno 2] No such file or directory: '/home/kkiefer/code/yocto/poky/build/tmp/deploy/ipk/armv8a_tegra194/libdrm-dev_2.4.100-r0.1_armv8a_tegra194.ipk' -> '/home/kkiefer/code/yocto/poky/build/tmp/work/mymachine-oe-linux/runtime-image/1.0-r0/oe-rootfs-repo/armv8a_tegra194/libdrm-dev_2.4.100-r0.1_armv8a_tegra194.ipk'
```

I can see the following in my deploy directory:

```
/home/kkiefer/code/yocto/poky/build/tmp/deploy/ipk/armv8a_tegra194/libdrm-dev_32.3.1-r0.2_armv8a_tegra194.ipk
/home/kkiefer/code/yocto/poky/build/tmp/deploy/ipk/armv8a_tegra194/morgue/libdrm-dev_2.4.100-r0.1_armv8a_tegra194.ipk
```

The lower-versioned libdrm-dev gets pushed into morgue in favor of the higher-versioned libdrm-dev, which is being provided by libdrm-nvdc. Deleting tmp, or cleaning out the libdrm and libdrm-nvdc makes the error go away for the build, but it comes back at some point, depending on the order libdrm gets staged relative to libdrm-nvdc.

libdrm-nvdc is deploying its copy of `libdrm.so.2` to a different directory, and it has this library marked as `PRIVATE_LIBS`. This is working fine. The problem appears when libdrm-nvdc adds the symlink from `tegra/libdrm.so.2` to `libdrm_nvdc.so`, because skipping this step during do_install, the issue goes away. So this sort of smells like a problem with the OE shared library resolver, but I'll start by raising a flag here in case you have some other ideas.

**Comment by madisongh** [comment]
I had fixed this for the main libdrm-nvdc package, but missed the -dev and -dbg packages.   Should be fixed now.  Thanks!
