### ISSUE TITLE
NVIDIA_DEVNET_MIRROR requirements for core-image-base builds

### ISSUE THREAD

**Issue by dwalkes** [madisongh/meta-tegra#292]
Hi @madisongh

This relates to discussion in #284

I think it would be great if people can get through mender setup with `core-image-base` without needing to mess with nvidia download tools, but if they can't I suppose should [update the documentation](https://github.com/Trellis-Logic/meta-mender-community/pull/11/files#diff-0ec18d144f9cf241f0b0b45d965806f5R51) to provide a link to the instructions about this.  I was preparing the [zeus meta-mender-community](https://github.com/Trellis-Logic/meta-mender-community/pull/11) branch and noticed zeus-l4t-r32.3.1 build fails without `NVIDIA_DEVNET_MIRROR` defined.

```
ERROR: Nothing PROVIDES 'tegra-mmapi-glheaders' (but /home/dan/mender-tegra/build/../sources/meta-tegra/recipes-graphics/libglvnd/libglvnd_1.2.0.bb DEPENDS on or otherwise requires it)
tegra-mmapi-glheaders was skipped: Recipe requires NVIDIA_DEVNET_MIRROR setup

ERROR: Required build target 'core-image-base' has no buildable providers.
Missing or unbuildable dependency chain was: ['core-image-base', 'packagegroup-base-extended', 'ofono', 'bluez5', 'python3-pygobject', 'cairo', 'virtual/libgles2', 'tegra-mmapi-glheaders']
```
However, cherry-picking https://github.com/madisongh/meta-tegra/commit/fb4f2fb3346b7f26e1a4296dd7c48d1333d88ee3 onto the zeus-l4t-r32.3.1 branch of meta-tegra resolves the issue and I can build core-image-base without `NVIDIA_DEVNET_MIRROR` on both `jetson-tx2` and `jetson-nano-qspi-sd` which are the two officially supported mender platforms.

Do you think it makes sense to plan to support `core-image-base` + mender without `NVIDIA_DEVNET_MIRROR` on warrior and later branches and, if so, would it be possible to get https://github.com/madisongh/meta-tegra/commit/fb4f2fb3346b7f26e1a4296dd7c48d1333d88ee3 cherry-picked into the zeus-l4t-r32.3.1 branch or would you like a new PR for this?

Thanks!

**Comment by madisongh** [comment]
Yeah, I held off on back-porting fb4f2fb for a couple of reasons - I wanted to be sure that builds checked out OK on master, and I didn't want to trigger massive rebuilds because of the change.

Builds on master seem to be checking out OK, and since this would generally be a desirable improvement, that probably outweighs the rebuild issue.  I'll go ahead and back-port the change.
