### ISSUE TITLE
tegraflash no rootfs?

### ISSUE THREAD

**Issue by rectoyon** [madisongh/meta-tegra#31]
@madisongh i'm following the instructions at the end of this issue https://github.com/madisongh/meta-tegra/issues/12. The one difference being I'm using core-image-minimal

it seems to go ok but it doesn't appear to flash a kernel or rootfs. After it reboots I just get a u-boot prompt. the doflash.sh happens very quickly but does seem to end ok
```
[   3.2199 ] Flashing completed

[   3.2199 ] Coldbooting the device
[   3.2206 ] tegradevflash --reboot coldboot
[   3.2211 ] Cboot version 00.01.0000
[   3.2231 ] 
```

Is there a next step I need to do?

**Comment by madisongh** [comment]
Can you try core-image-base instead, or add ${MACHINE_EXTRA_RRECOMMENDS} to your core-image-minimal images?  I think I need to move a couple of the packages listed in that variable to MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS instead, so the kernel image, device tree, and extlinux.conf file get installed in `/boot`.

You may also need to explicitly set IMAGE_ROOTFS_ALIGNMENT to "4096" as mentioned in that other thread.

**Comment by paroque28** [comment]
If anyone needs this information... this could also happen if you forget to remove the following configuration:
`TNSPEC_BOOTDEV = "nvme0n1p1"`
