### ISSUE TITLE
Attempt to build yocto on Ubuntu Xavier NX result in.

### ISSUE THREAD

**Issue by outbackdingo** [madisongh/meta-tegra#339]
So I bought an Xavier NX dev kit, thinking id add a desktop UI, it runs the NVIDIA Ubuntu image.... 
attempting to build a yocto image for the Nano...

dingo@xavier-nx-desktop:~/yocto/nano$ bitbake core-image-minimal
Parsing recipes: 100% |#########################################################################################################################| Time: 0:01:13
Parsing of 867 .bb files complete (0 cached, 867 parsed). 1450 targets, 104 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION           = "1.46.0"
BUILD_SYS            = "aarch64-linux"
NATIVELSBSTRING      = "ubuntu-18.04"
TARGET_SYS           = "aarch64-oe-linux"
MACHINE              = "jetson-nano-qspi-sd"
DISTRO               = "nodistro"
DISTRO_VERSION       = "nodistro.0"
TUNE_FEATURES        = "aarch64 armv8a crc"
TARGET_FPU           = ""
meta                 
meta-poky            
meta-yocto-bsp       = "dunfell:6436d102f15a129384d980f65b02b86fc52ae77a"
meta-tegra           = "dunfell:a0144696dd2d174ad920da80ecc0b3fc93ffce19"

Initialising tasks: 100% |######################################################################################################################| Time: 0:00:04
Sstate summary: Wanted 635 Found 0 Missed 635 Current 0 (0% match, 0% complete)
NOTE: Executing Tasks
ERROR: tegra210-flashtools-native-32.3.1-r0 do_populate_sysroot: Fatal errors occurred in subprocesses:
Command '['strip', '--remove-section=.comment', '--remove-section=.note', '/home/dingo/yocto/nano/tmp-glibc/work-shared/L4T-native-tegra210-32.3.1-r0/sysroot-destdir/home/dingo/yocto/nano/tmp-glibc/work-shared/L4T-native-tegra210-32.3.1-r0/recipe-sysroot-native/usr/bin/tegra210-flash/mksparse']' returned non-zero exit status 1.
Subprocess output:strip: Unable to recognise the format of the input file `/home/dingo/yocto/nano/tmp-glibc/work-shared/L4T-native-tegra210-32.3.1-r0/sysroot-destdir/home/dingo/yocto/nano/tmp-glibc/work-shared/L4T-native-tegra210-32.3.1-r0/recipe-sysroot-native/usr/bin/tegra210-flash/mksparse'
Command '['strip', '--remove-section=.comment', '--remove-section=.note', '/home/dingo/yocto/nano/tmp-glibc/work-shared/L4T-native-tegra210-32.3.1-r0/sysroot-destdir/home/dingo/yocto/nano/tmp-glibc/work-shared/L4T-native-tegra210-32.3.1-r0/recipe-sysroot-native/usr/bin/tegra210-flash/tegradevflash']' returned non-zero exit status 1.
Subprocess output:strip: Unable to recognise the format of the input file `/home/dingo/yocto/nano/tmp-glibc/work-shared/L4T-native-tegra210-32.3.1-r0/sysroot-destdir/home/dingo/yocto/nano/tmp-glibc/work-shared/L4T-native-tegra210-32.3.1-r0/recipe-sysroot-native/usr/bin/tegra210-flash/tegradevflash'
Command '['strip', '--remove-section=.comment', '--remove-section=.note', '/home/dingo/yocto/nano/tmp-glibc/work-shared/L4T-native-tegra210-32.3.1-r0/sysroot-destdir/home/dingo/yocto/nano/tmp-glibc/work-shared/L4T-native-tegra210-32.3.1-r0/recipe-sysroot-native/usr/bin/tegra210-flash/tegrasign']' returned non-zero exit status 1.
Subprocess output:strip: Unable to recognise the format of the input file `/home/dingo/yocto/nano/tmp-glibc/work-shared/L4T-native-tegra210-32.3.1-r0/sysroot-destdir/home/dingo/yocto/nano/tmp-glibc/work-shared/L4T-native-tegra210-32.3.1-r0/recipe-sysroot-native/usr/bin/tegra210-flash/tegrasign'
Command '['strip', '--remove-section=.comment', '--remove-section=.note', '/home/dingo/yocto/nano/tmp-glibc/work-shared/L4T-native-tegra210-32.3.1-r0/sysroot-destdir/home/dingo/yocto/nano/tmp-glibc/work-shared/L4T-native-tegra210-32.3.1-r0/recipe-sysroot-native/usr/bin/tegra210-flash/mkbctpart']' returned non-zero exit status 1.
Subprocess output:strip: Unable to recognise the format of the input file `/home/dingo/yocto/nano/tmp-glibc/work-shared/L4T-native-tegra210-32.3.1-r0/sysroot-destdir/home/dingo/yocto/nano/tmp-glibc/work-shared/L4T-native-tegra210-32.3.1-r0/recipe-sysroot-native/usr/bin/tegra210-flash/mkbctpart'
Command '['strip', '--remove-section=.comment', '--remove-section=.note', '/home/dingo/yocto/nano/tmp-glibc/work-shared/L4T-native-tegra210-32.3.1-r0/sysroot-destdir/home/dingo/yocto/nano/tmp-glibc/work-shared/L4T-native-tegra210-32.3.1-r0/recipe-sysroot-native/usr/bin/tegra210-flash/tegrahost']' returned non-zero exit status 1.
Subprocess output:strip: Unable to recognise the format of the input file `/home/dingo/yocto/nano/tmp-glibc/work-shared/L4T-native-tegra210-32.3.1-r0/sysroot-destdir/home/dingo/yocto/nano/tmp-glibc/work-shared/L4T-native-tegra210-32.3.1-r0/recipe-sysroot-native/usr/bin/tegra210-flash/tegrahost'
Command '['strip', '--remove-section=.comment', '--remove-section=.note', '/home/dingo/yocto/nano/tmp-glibc/work-shared/L4T-native-tegra210-32.3.1-r0/sysroot-destdir/home/dingo/yocto/nano/tmp-glibc/work-shared/L4T-native-tegra210-32.3.1-r0/recipe-sysroot-native/usr/bin/tegra210-flash/mkpkc']' returned non-zero exit status 1.
Subprocess output:strip: Unable to recognise the format of the input file `/home/dingo/yocto/nano/tmp-glibc/work-shared/L4T-native-tegra210-32.3.1-r0/sysroot-destdir/home/dingo/yocto/nano/tmp-glibc/work-shared/L4T-native-tegra210-32.3.1-r0/recipe-sysroot-native/usr/bin/tegra210-flash/mkpkc'

ERROR: Logfile of failure stored in: /home/dingo/yocto/nano/tmp-glibc/work-shared/L4T-native-tegra210-32.3.1-r0/temp/log.do_populate_sysroot.4535
ERROR: Task (/home/dingo/yocto/meta-tegra/recipes-bsp/tegra-binaries/tegra210-flashtools-native_32.3.1.bb:do_populate_sysroot) failed with exit code '1'
NOTE: Tasks Summary: Attempted 550 tasks of which 0 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/dingo/yocto/meta-tegra/recipes-bsp/tegra-binaries/tegra210-flashtools-native_32.3.1.bb:do_populate_sysroot
Summary: There was 1 ERROR message shown, returning a non-zero exit code.

**Comment by madisongh** [comment]
You should be able to work around the error by adding

`INHIBIT_SYSROOT_STRIP_pn-tegra210-flashtools-native = "1"`

in your `local.conf`, but I've pushed a fix to the recipe to make sure that's set, since there's no reason to be trying to strip those binaries ever.  It's just on x86-64 hosts we don't see a failure.

Even with that in place, I'm not sure this setup will work. The NVIDIA host-side flashing tools are binary-only and x86-64 only, so you'll at least need the necessary qemu and binfmt packages installed to run them.  There may well be other issues, too, and it may not be possible to make this setup work at all.
