### ISSUE TITLE
docker-nvidia binary vs git 

### ISSUE THREAD

**Issue by outbackdingo** [madisongh/meta-tegra#345]
curious it seems if using docker we can deploy docker-nvidia from the dev sdk, however its binary, i also found https://github.com/NVIDIA/nvidia-docker.git i was curious if it might be best to create a recipe to build it from sources?

**Comment by madisongh** [comment]
We do build it from sources here.  See the recipes under [recipes-containers](https://github.com/madisongh/meta-tegra/tree/master/recipes-containers).

**Comment by outbackdingo** [comment]
got it, thanks again!
