### ISSUE TITLE
Generation of multi target bup

### ISSUE THREAD

**Issue by klakaiser** [madisongh/meta-tegra#351]
Hello, 
i have a question about the generation of bup payloads. Is it possible to generate some kind of multi target payloads? I would like to generate a single payload that can be used for the different hardware revisions of TX2 hardware which is around.

Thanks,
Klaus

**Comment by madisongh** [comment]
All of the branches based off L4T R32.3.1 and later generate multi-spec BUP payloads, similar to the `l4t_generate_soc_bup.sh` script that comes with L4T. The TEGRA_BUPGEN_SPECS variable controls the set of specs used.

**Comment by klakaiser** [comment]
Thank you very much for this quick info and your great work on meta-tegra.
