### ISSUE TITLE
Can't see omx plugins in TX2

### ISSUE THREAD

**Issue by rectoyon** [madisongh/meta-tegra#37]
This appears to be similar to #20.

I have this in my IMAGE_INSTALL +=
```
    gstreamer1.0 \
    gstreamer1.0-meta-base \
    gstreamer1.0-omx-tegra \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-base \
    gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-nveglgles \
    gstreamer1.0-plugins-tegra \
    gstreamer1.0-vaapi \
```
But, I can't see any omx plugins
```
root@jetson-tx2:/mnt/gstpipes# gst-inspect-1.0 | grep omx
root@jetson-tx2:/mnt/gstpipes# 
```

I did try this from #20 
```
DISTRO_FEATURES_append = " x11"
```
which I feel like I successfully used on TX1 but can't remember.

**Comment by madisongh** [comment]
Turns out it was a missing symbol due to some changes in R27.1.  I added a patch to fix it, and the OMX plugin is working again.

**Comment by rectoyon** [comment]
thanks!
