### ISSUE TITLE
modify and compile device tree jetson-tx2

### ISSUE THREAD

**Issue by GencerG** [madisongh/meta-tegra#370]
Hi,
I'm trying to enable MCP2515 spi-canbus on Jetson TX2. I need to modify .dts file, and rebuild my boot2qt image. What would be the best way of doing it ? 
Thank you.

**Comment by madisongh** [comment]
Which branch are you based off of?  With older branches, config changes are best done by overriding the `defconfig` file with a modified copy in your layer ([example here](https://github.com/madisongh/test-distro/blob/zeus/layers/meta-testdistro/recipes-kernel/linux/linux-tegra_4.9.bbappend)).  More recently, we switched to using the linux-yocto tooling, which provides for configuration fragments to be applied ([example here](https://github.com/madisongh/test-distro/blob/dunfell-l4t-r32.4.2/layers/meta-testdistro/recipes-kernel/linux/linux-tegra_4.9.bbappend)).

Modifying the device tree involves either applying a patch or forking the [linux-tegra-4.9](https://github.com/madisongh/linux-tegra-4.9) repository, making the necessary changes there, and using a bbappend file to modify the SRC_URI and SRCREV settings to point to your changes.
