### ISSUE TITLE
cuda-misc-headers needed by cuda-misc-headers-dev

### ISSUE THREAD

**Issue by ilyaikik** [madisongh/meta-tegra#63]
When _bitbake 'image' -c populate_sdk_ with _cuda-misc-headers-dev_ in " RDEPENDS_${PN} += " path of my .bbappend file for toolchain-target I see bitbake error with:
_.....
nothing provides cuda-misc-headers = 8.0.84+1-r0 needed by cuda-misc-headers-dev-8.0.84+1-r0.aarch64_tegra186
....._

So, adding 
`RDEPENDS_${PN}-dev = "" `
in the end of _recipes-devtools/cuda/cuda-misc-headers_8.0.84-1.bb_ solves the problem.

I'm using _pyro-l4t-r28.1_ , compiling for Jetson-tx2.

**Comment by madisongh** [comment]
Yep, that would be the right fix.
