### ISSUE TITLE
devicequery segmentation fault

### ISSUE THREAD

**Issue by markhamj** [madisongh/meta-tegra#68]
Tied a couple different approaches to running deviceQuery on Jetson TX2.  Segfaults every time.  I'm fairly certain it has to do with mismatches in library versions etc.

Is there a way to build it as part of generating the image?   Can I generate an SDK that will allow me to build it and match the versions?

**Comment by madisongh** [comment]
Is that one of the CUDA sample programs?  How are you trying to build it?  I could take a look at putting a recipe in place for it and maybe some of the other samples.  I'm no CUDA expert, though.

**Comment by madisongh** [comment]
I have added a recipe to extract the CUDA samples and build a couple of the simple ones (including deviceQuery).  I tested the cross-built sample programs on my Jetson-TX2, and they ran OK.

Hope this helps.

**Comment by markhamj** [comment]
Thanks.  I’ll give it a try and let you know
