### ISSUE TITLE
cuda 9 with l4t-r28.1

### ISSUE THREAD

**Issue by ElioDream** [madisongh/meta-tegra#79]
Hi @madisongh,
I fell back to l4t-r28.1 to use Connect Tech's BSP, and I was wondering if you tried to use cuda-9 with r28.1 ? The default recipes are cuda-8, do you think that I'd only need to take the cuda-9 recipes instead ?
Elio

EDIT : 
Okay, my image compiled so I guess what I did was enough. Namely, copy the cuda-9 recipes to my own meta, AND copy the ./external directory which contains a patch for opencv3.3. Last step, modify conf/layer.conf to warn bitbake that there are some files in external, as you did in your layer.conf

**Comment by madisongh** [comment]
I don't know whether this would actually work, even if you copied over libcuda.so from the 28.2 driver package.  It's hard enough making even the NVIDIA-supported configurations work reliably.

**Comment by ElioDream** [comment]
I'll tell you as soon as I can test it
