### ISSUE TITLE
opencv recipe fails with nothing provides libopencv-ts

### ISSUE THREAD

**Issue by lfdmn** [madisongh/meta-tegra#82]
On branch pyro-l4t-r28.1 adding opencv to the image fails with "Nothing provides libopencv-ts"

Browsing the web points to the test library being built as static library instead of shared. But the patches for fixing this issue are already applied. At least I think so.
* 0001-Make-opencv-ts-create-share-library-intead-of-static.patch
* 0001-To-fix-errors-as-following.patch

For now I added -DBUILD_TESTS=OFF to EXTRA_OECMAKE to prevent building the test library but I don't know how to really fix the issue.

**Comment by madisongh** [comment]
I've never run into this, but I don't usually try to include all of opencv in my images.  I just include applications that link against opencv libraries, and let the build system pull in whatever libraries that get linked into those apps.  Setting BUILD_TESTS to OFF is probably a good solution, unless you need the tests.

**Comment by lfdmn** [comment]
Closing this issues. I disabled building the test module.
