### ISSUE TITLE
git history rewrite

### ISSUE THREAD

**Issue by floion** [madisongh/meta-tegra#87]
Hi guys,
we are using meta-tegra as a git submodule. This was pinned at version wip-rocko-l4t-r28.2 (with revision a320e8d7560e6a1fb6c36feacc449f767f6b01d7).
Today apparently that revision is missing (whole branch has been wiped out). Was the git history rewritten by accident? Or was it intentional (it has the wip label but the expectation was git history stays untouched )? We need to asses if this can happen in the future.
Thank you

**Comment by madisongh** [comment]
Yeah, sorry, I use the 'wip-' prefix on any work in progress, and branches with that prefix can either get rebased while work is in progress, and deleted once the work is done.  I have restored that branch from another copy I had sitting around, but I'd recommend switching over to the current `rocko-l4t-r28.2` branch.
